/** Reviewed object families — one canonical normalize value per option. */
export const DEFAULT_OBJECT_VALUE = 'telescope';

export const OBJECT_OPTIONS = [
  { label: '3D printer', value: '3D printer', objectClass: 'THREE_D_PRINTER' },
  { label: '3D scanner', value: '3D scanner', objectClass: 'THREE_D_SCANNER' },
  { label: 'Air compressor', value: 'air compressor', objectClass: 'AIR_COMPRESSOR' },
  { label: 'Binoculars', value: 'binoculars', objectClass: 'BINOCULARS' },
  { label: 'Board game', value: 'board game', objectClass: 'BOARD_GAME' },
  { label: 'Book club kit', value: 'book club kit', objectClass: 'BOOK_CLUB_KIT' },
  { label: 'Circular saw', value: 'circular saw', objectClass: 'CIRCULAR_SAW' },
  { label: 'Electricity usage meter', value: 'electricity usage meter', objectClass: 'ELECTRICITY_USAGE_METER' },
  { label: 'Fishing pole', value: 'fishing pole', objectClass: 'FISHING_POLE' },
  { label: 'Garden tool', value: 'garden tool', objectClass: 'GARDEN_TOOL' },
  { label: 'Guitar', value: 'guitar', objectClass: 'MUSICAL_INSTRUMENT' },
  { label: 'Hedge trimmer', value: 'hedge trimmer', objectClass: 'HEDGE_TRIMMER' },
  { label: 'Home repair tool', value: 'home repair tool', objectClass: 'HOME_REPAIR_TOOL' },
  { label: 'Jigsaw', value: 'jigsaw', objectClass: 'JIG_SAW' },
  { label: 'Kids activity tablet', value: 'kids activity tablet', objectClass: 'KIDS_ACTIVITY_TABLET' },
  { label: 'Knitting loom', value: 'knitting loom', objectClass: 'KNITTING_LOOM' },
  { label: 'Ladder', value: 'ladder', objectClass: 'LADDER' },
  { label: 'Laser engraver', value: 'laser engraver', objectClass: 'LASER_ENGRAVER' },
  { label: 'Mobile hotspot', value: 'mobile hotspot', objectClass: 'MOBILE_HOTSPOT' },
  { label: 'OBD-II scanner', value: 'OBD-II scanner', objectClass: 'OBD2_SCANNER' },
  { label: 'Portable CD player', value: 'portable cd player', objectClass: 'PORTABLE_CD_PLAYER' },
  { label: 'Portable DVD player', value: 'portable dvd player', objectClass: 'PORTABLE_DVD_PLAYER' },
  { label: 'Power tool', value: 'power tool', objectClass: 'POWER_TOOL' },
  { label: 'Pressure washer', value: 'pressure washer', objectClass: 'PRESSURE_WASHER' },
  { label: 'Reciprocating saw', value: 'reciprocating saw', objectClass: 'RECIPROCATING_SAW' },
  { label: 'Sander', value: 'sander', objectClass: 'SANDER' },
  { label: 'Science kit', value: 'science kit', objectClass: 'SCIENCE_STEAM_KIT' },
  { label: 'Sewing machine', value: 'sewing machine', objectClass: 'SEWING_MACHINE' },
  { label: 'Soldering station', value: 'soldering station', objectClass: 'SOLDERING_STATION' },
  { label: 'Telescope', value: 'telescope', objectClass: 'TELESCOPE' },
  { label: 'Tiller', value: 'tiller', objectClass: 'TILLER' },
  { label: 'Ukulele', value: 'ukulele', objectClass: 'UKULELE' },
  { label: 'Video transfer equipment', value: 'video transfer equipment', objectClass: 'VIDEO_TRANSFER_EQUIPMENT' },
  { label: 'Vinyl cutter', value: 'vinyl cutter', objectClass: 'VINYL_CUTTER' },
  { label: 'Wet-dry vacuum', value: 'wet-dry vacuum', objectClass: 'WET_DRY_VACUUM' },
];
