/** Generated by scripts/generate-national-data.mjs — do not edit. */
export const IMLS_SEARCH_COMPARE_URL = "https://www.imls.gov/search-compare";
export const NATIONAL_REVIEW_DATE = "2026-09-12";
export const NATIONAL_PACKET = "CIBT-NATIONAL-TRANSFER-002";
export const ROUTE_CLASS = {"E":"EXACT_IMLS_OUTLET_ZIP","S":"EXACT_IMLS_SYSTEM_ZIP","Z":"ZCTA_NEAREST_ACTIVE_OUTLET","I":"OBSERVED_REFERENCE_INDIRECT_ONLY"};
export const ROUTE_CLASS_COUNTS = {"EXACT_IMLS_OUTLET_ZIP":15300,"EXACT_IMLS_SYSTEM_ZIP":49,"OBSERVED_REFERENCE_INDIRECT_ONLY":3980,"ZCTA_NEAREST_ACTIVE_OUTLET":18536};
export const NATIONAL_TRANSFER_COUNTS = {
  systems: 9200,
  outlets: 17415,
  observedRoutingIdentifiers: 37865,
  zctas: 33791,
  centers: 151,
  statesPlusDc: 51,
  deterministicBytes: 7990411,
};
export const NATIONAL_TRANSFER_HASHES = {"national_centers_151.csv":"7730850bb716803b4186bdd334eb0df12b566326edc3c8b676f751e8c4e18ee7","national_destinations.csv":"0ad7ff3b0869c567f1e70a01551b209a19df81a15899b068202fbeb44c1cba42","national_geo_outlets.csv":"738a7fdd6703a51beb854725076484ba1938d17afc0a95c2441d55eb298c6bfc","national_transfer_manifest.json":"c0fc6e440ac9073e2fc7d09fd333d20a90b6deb305e03ba127e6314587b42a21","national_zip_routes.csv":"0ed4e3389a6938a28a8d0b963589488d53884327f207a34e52405bdea466b5f7"};
export const NATIONAL_STATES = ["AK","AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","HI","IA","ID","IL","IN","KS","KY","LA","MA","MD","ME","MI","MN","MO","MS","MT","NC","ND","NE","NH","NJ","NM","NV","NY","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VA","VT","WA","WI","WV","WY"];
export const NATIONAL_ASSET_BYTES = {
  destinationsJson: 2361605,
  outletsJson: 3274754,
  routeChunksTotal: 1725793,
  routeChunkCount: 99,
};
